parameters:
  PreSteps: []
  PostSteps: []
  EnvVars: {}
  MaxParallel: 0
  BuildInParallel: true
  TimeoutInMinutes: 60

jobs:
  - job: "Test"
    variables:
      - template: ../variables/globals.yml

    timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}

    strategy:
      maxParallel: ${{ parameters.MaxParallel }}
      matrix:
        # US Government
        Linux (AzureUSGovernment):
          OSName: "Linux"
          OSVmImage: "ubuntu-16.04"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureUSGovernment
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
        Windows_NetCoreApp (AzureUSGovernment):
          OSName: "Windows"
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureUSGovernment
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
        Windows_NetCoreApp_ProjectReferences (AzureUSGovernment):
          OSName: "Windows"
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureUSGovernment
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
          ConvertToProjectReferenceOption: /p:UseProjectReferenceToAzureClients=true
        Windows_NetFramework (AzureUSGovernment):
          OSName: "Windows"
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
          CloudType: AzureUSGovernment
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)
        MacOs (AzureUSGovernment):
          OSName: "MacOS"
          OSVmImage: "macOS-10.15"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureUSGovernment
          ArmTemplateParameters: $(azureUSGovernmentArmParameters)

        # China Cloud
        Linux (AzureChinaCloud):
          OSName: "Linux"
          OSVmImage: "ubuntu-16.04"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureChinaCloud
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
        Windows_NetCoreApp (AzureChinaCloud):
          OSName: "Windows"
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureChinaCloud
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
        Windows_NetCoreApp_ProjectReferences (AzureChinaCloud):
          OSName: "Windows"
          OSVmImage: "windows-2019"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureChinaCloud
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
          ConvertToProjectReferenceOption: /p:UseProjectReferenceToAzureClients=true
        Windows_NetFramework (AzureChinaCloud):
          OSName: "Windows"
          OSVmImage: "windows-2019"
          TestTargetFramework: net461
          CloudType: AzureChinaCloud
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
        MacOs (AzureChinaCloud):
          OSName: "MacOS"
          OSVmImage: "macOS-10.15"
          TestTargetFramework: netcoreapp2.1
          CloudType: AzureChinaCloud
          ArmTemplateParameters: $(azureChinaCloudArmParameters)
    pool:
      vmImage: "$(OSVmImage)"

    variables:
      azureCloudArmParameters: "@{ storageEndpointSuffix = 'core.windows.net'; azureCloud = 'AzureCloud'; }"
      azureUSGovernmentArmParameters: "@{ storageEndpointSuffix = 'core.usgovcloudapi.net'; azureCloud = 'AzureUSGovernment'; }"
      azureChinaCloudArmParameters: "@{ storageEndpointSuffix = 'core.chinacloudapi.cn'; azureCloud = 'AzureChinaCloud'; }"


    steps:
      - ${{ parameters.PreSteps }}

      - template: eng/pipelines/templates/scripts/verify-agent-os.yml@azure-sdk-tools
        parameters:
          OSName: $(OSName)

      - task: UseDotNet@2
        displayName: "Use .NET Core runtime $(DotNetCoreRuntimeVersion)"
        inputs:
          packageType: runtime
          version: "$(DotNetCoreRuntimeVersion)"

      - task: UseDotNet@2
        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
        inputs:
          packageType: sdk
          version: "$(DotNetCoreSDKVersion)"

      - template: /eng/common/TestResources/deploy-test-resources.yml
        parameters:
          ServiceDirectory: '${{ parameters.ServiceDirectory }}'

      - script: >
          dotnet test eng/service.proj
          --framework $(TestTargetFramework)
          --logger "trx;LogFileName=$(TestTargetFramework).trx"
          --logger:"console;verbosity=normal"
          /p:ServiceDirectory=${{ parameters.ServiceDirectory }}
          /p:IncludeSrc=false /p:IncludeSamples=false
          /p:BuildInParallel=${{ parameters.BuildInParallel }}
          $(ConvertToProjectReferenceOption)

        displayName: "Build & Test (all tests for $(TestTargetFramework))"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
          AZURE_TEST_MODE: "None"
          ${{ insert }}: ${{ parameters.EnvVars }}

      - template: /eng/common/TestResources/remove-test-resources.yml

      - task: PublishTestResults@2
        condition: always()
        displayName: "Publish Results ($(TestTargetFramework))"
        inputs:
          testResultsFiles: "**/$(TestTargetFramework)*.trx"
          testRunTitle: "$(OSName) $(TestTargetFramework)"
          testResultsFormat: "VSTest"
          mergeTestResults: true

      - ${{ parameters.PostSteps }}
